name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    uses: yasyf/homebrew-tap/.github/workflows/release-go.yml@a0015cd88d2e6bef1a5c475a4e2cad5d875c7f47
    secrets: inherit
